
name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ghcr.io/${{ github.repository }}/wisecow:${{ github.sha }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU (optional)
      uses: docker/setup-qemu-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/wisecow:latest
          ghcr.io/${{ github.repository }}/wisecow:${{ github.sha }}

  deploy-local:
    # This job runs on your self-hosted runner that has kubectl and access to your cluster
    runs-on: [ self-hosted, local-deploy ]
    needs: build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull latest image
        run: |
          # pull from GHCR on your local machine
          podman pull ghcr.io/${{ github.repository }}/wisecow:latest
          podman tag ghcr.io/${{ github.repository }}/wisecow:latest local/wisecow:latest

      - name: kubectl apply manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
